# Site settings
title: D3 Test
description: "Test Class Project"
url: "https://testx.github.io"


# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]